### ISSUE TITLE
[Batch Viewer] Disable the reset button

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/explorer#101]
**Description**
By default the reset button appears when the batch viewer is opened (there is no view to reset yet).
![image](https://user-images.githubusercontent.com/622217/170525518-3e08fd67-22ca-4e73-a3fb-a0f41a7fd73e.png)

**Proposal**
Disable the button and change the state only when the zoom/panning changed.

Example:
![image](https://user-images.githubusercontent.com/622217/170526688-275feb95-5189-4f03-8464-6d89414e9056.png)
Also add the CSS property:    ` cursor: not-allowed;`

**Comment by elena-zh** [comment]
I would add this cases here as it will be resolved by disabling Reset button: 
1. Currently, the diagram is [moving](https://watch.screencastify.com/v/D9zb8SYr8eLnktLvttRe) when press on the Reset button on the default view chart
2. In this [transaction ](https://pr119--explorer.review.gnosisdev.com/tx/0xc247e6ecdad9a20135400844b123f20b18e6fe2e69001d5b9bc919fa2fb0ead4/?tab=graph)with klay layout [2 arrows are always blinking ](https://watch.screencastify.com/v/N8k33yb6FA8bUndc3yOb)when press on the Reset button
