### ISSUE TITLE
No TxHash in an order when open last batch link

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#138]
Related to #137

1. Open Home page
2. Press on the Last batch ID 
3. Open order details

**AR**: no TX hash for this order
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/0e86e401-e7fc-4da6-b6a1-38cd0bdb4edd)
**ER**: TxHash should present

**Comment by ramirotw** [comment]
Fixed by https://github.com/cowprotocol/explorer/pull/132
