### ISSUE TITLE
Get Support link from search not found page navigates to https://discord.com/

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#140]
1. Open Explorer Home page
2. Search for an order that does not exist
3. Press on the Get support link

**AR**: Get Support link  navigates to https://discord.com/

**ER**: Get Support link  navigates to https://discord.com/invite/cowprotocol

**Comment by ramirotw** [comment]
Closed by https://github.com/cowprotocol/explorer/pull/144
