### ISSUE TITLE
Show a TxHash for a partially filled orders

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#165]
Discussed in https://github.com/cowprotocol/explorer/issues/155#issuecomment-1188904414

Each fill/trade will have a different tx hash a be part of a different batch.

There is a wireframe design made since the beginning for this which has never been prioritized https://www.figma.com/file/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=0%3A1

![Screen Shot 2022-07-19 at 11 47 29](https://user-images.githubusercontent.com/43217/179732871-6ba71834-1cf5-4a0d-b907-1ac8589486b0.png)

Account with partially filled order:
https://protocol-explorer.dev.gnosisdev.com/rinkeby/address/0xDe1E8EedD42CD284a3052d987502d0B24c633FEE

**Comment by alongoni** [comment]
Here we have a draft design for partially filled orders:
- Iteration 1 (show list of txs):
![UI_Explorer - iteration 1 - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/192395289-46007771-2bc8-42f0-97ba-7d92fdcbb44b.png)

- Iteration 2 (tabs):
![UI_Explorer - Iteration 2 Overview - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/192395306-925af4b8-40b2-45dc-9c5b-10bb7c26a2bc.png)
![UI_Explorer - Iteration 2 Fills  - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/192395537-078e6096-48ea-4212-913f-bc4e9d878e5e.png)

cc @alfetopito @anxolin @ramirotw

**Comment by elena-zh** [comment]
Hey @alongoni , great job!
As for Iteration 2, I don't see BV button for each transaction. 
I'm not sure whether it needed, but as it exists for the 1st iteration, it should remain for the 2nd one, from my perspective.

Also, I'm a bit confused with 'Execution time' column, as now a TX endpoint returns 'creationDate' only 
![image](https://user-images.githubusercontent.com/70885163/192482390-44a512d9-6832-4e69-8320-3dd88b97750f.png)
Will it be possible to show 'Execution time' or it would be better to rename the column to 'Created'?

Thanks!

**Comment by alfetopito** [comment]
Thanks Agustin, looks great!

> Hey @alongoni , great job! As for Iteration 2, I don't see BV button for each transaction. I'm not sure whether it needed, but as it exists for the 1st iteration, it should remain for the 2nd one, from my perspective.

Agree
 
> Also, I'm a bit confused with 'Execution time' column, as now a TX endpoint returns 'creationDate' only ![image](https://user-images.githubusercontent.com/70885163/192482390-44a512d9-6832-4e69-8320-3dd88b97750f.png) Will it be possible to show 'Execution time' or it would be better to rename the column to 'Created'?

You are partially right Elena, we don't have execution date returned from `/transactions/<>/orders` API unfortunately. 

Although, the data we use here will come from the `/trades` endpoint instead, which also doesn't return `execution date`, but returns something very close to it, which is the `blockNumber`

![Screen Shot 2022-09-27 at 11 18 11](https://user-images.githubusercontent.com/43217/192500528-5360b730-5874-4ada-afa9-05aaa565e767.png)

With the blockNumber we can get that extra data with a network call, so I think it's fine to have the column as Agustin suggests

Now the Surplus will be tricky.
I thought about this awhile ago and there might be a way to calculate it based on the execution price, but I'm not 100% sure on the math. Let's keep it for now and decide during implementation.

**Comment by alongoni** [comment]
Design updates on "fill" tab.
![UI_Explorer - Iteration 2 Fills  - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/192633031-f571c653-237d-497c-811c-04c59ba27653.png)

**Comment by fairlighteth** [comment]
In general I think this looks good. I have a few comments you could consider:
- I would try to tone down the light (unfilled) part of the bar with a darker color. Ideally a color we already use somewhere in the UI
<img width="174" alt="Screen Shot 2022-09-29 at 09 41 29" src="https://user-images.githubusercontent.com/31534717/192984051-95e59bc5-99fb-45e1-a3c0-52e71f80773c.png">

- In the OVERVIEW tab I would also make a text/link reference on the Filled row. Something along the lines of 'View fills' or 'View transactions'. On click it would do the same as clicking on the FILLS tab:
<img width="519" alt="Screen Shot 2022-09-29 at 09 42 21" src="https://user-images.githubusercontent.com/31534717/192984278-c8a7d330-fc86-4e43-8ecf-ae8a48a7390d.png">

- As to @alfetopito 's comment on the FILLED title text being redudant: I would favor being explicit here and keep it. Also the idea is that later we can add more 'widgets' e.g. to show the amount of accumulative generate surplus based on the filled % of the order.

**Comment by alongoni** [comment]
Design updated:
![UI_Explorer - Iteration 2 Overview - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/193302088-f1fb330f-e537-401f-b50c-2913f87e28db.png)
![UI_Explorer - Iteration 2 Fills  - order detail page _ partially filled orders](https://user-images.githubusercontent.com/622217/193302094-fc883bed-cb37-40bd-8740-af2553051962.png)

cc @alfetopito @fairlighteth @ramirotw @elena-zh

**Comment by fairlighteth** [comment]
@alongoni Thanks for the changes, looks much better. As for this:
<img width="753" alt="Screen Shot 2022-09-30 at 16 54 05" src="https://user-images.githubusercontent.com/31534717/193309325-8a8f5bf4-abea-4b9d-b583-dff168c84a56.png">

The actual content can be variable in width, so the button will move around. Perhaps it's better to right align the button so it's at a fixed spot (or another way you find we can address this).

**Comment by anxolin** [comment]
@alfetopito low prio, but when we have time we can make sure is merged
