### ISSUE TITLE
AppData: Elements overlap each other on big screens 

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#193]
AppData: Elements overlap each other on big screens (3840x2160 as an example)
See the image: 

![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2e2eb515-85b1-4954-94cb-6e8d57365b7f)

**Expected**: elements do not overlap each other

**Comment by alongoni** [comment]
Fixed in https://github.com/cowprotocol/explorer/pull/189
