### ISSUE TITLE
NaN is displayed in the main page in Explorer in dev environment

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#196]
The issue is reproducible in https://protocol-explorer.dev.gnosisdev.com/ only (not in Barn/Staging/Prod)

To reproduce: 
Open https://protocol-explorer.dev.gnosisdev.com/, scroll down to Token page
Take a look to MM token (position 8 in Ethrerum network)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1c7bf6a1-cbb3-44c8-9bcb-1940813e81f0)

OR open https://protocol-explorer.dev.gnosisdev.com/gc and scroll down to AGVE token (position 9 in Top tokens table)

**AR**: NAN is displayed
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ed4a4f75-d619-4592-a367-57895c1866eb)
**ER**: 0 is displayed

**Comment by ramirotw** [comment]
Fixed in https://github.com/cowprotocol/explorer/pull/189

**Comment by alongoni** [comment]
Should we close this one?
