### ISSUE TITLE
Add  skeleton rows during table lines loading OR enhance a loading effect on Explorer pages

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#21]
Currently, loading circles are displayed in table lines when its data is loading. 
As an enhancement, I'd like to suggest to add skeleton rows to the table. As an example, something like this
https://github.com/tannerlinsley/react-table/discussions/2386

We could apply it for the whole line.

> Original issue https://github.com/gnosis/gp-ui/issues/862 by @elena-zh

**Comment by elena-zh** [comment]
Another option how to fix the loading is https://github.com/cowprotocol/explorer/pull/80#issuecomment-1117161217

**Comment by elena-zh** [comment]
It would be good to add this effect to the Top Tokens table (originally reported in https://github.com/cowprotocol/explorer/pull/81#issuecomment-1122261946 , p.5)
