### ISSUE TITLE
Add font property to the menu and action buttons on the AppData page

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#217]
Originally reported in https://github.com/cowprotocol/explorer/pull/214#issuecomment-1247961640
 it would be great to add 'font-family' param to the dropdown button as it looks different with the Home button option. See the comparison: 
 - without the param (the current view):
![without it looks different](https://user-images.githubusercontent.com/70885163/190390465-5984b68b-0f75-492b-85b8-2b0a3226f9f4.jpg)
 - with 'font-family' param:
![add a proprety](https://user-images.githubusercontent.com/70885163/190390568-41174392-dda0-4d55-bbc5-6fcee755676c.jpg)

The same is for the Action buttons on the AppData page: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f2573527-011c-4e3d-9042-08456a0ef40c)

**Comment by alongoni** [comment]
closed by #218

**Comment by alongoni** [comment]
closed by #218
