### ISSUE TITLE
[Order list] Column values are not left-aligned

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#22]
The issue is reproducible when a screen width is [1025-1065] px
Statuses become right-aligned
![left.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/318b9cea-613f-46ce-954a-e70010b48cae)

**Expected**: keep statuses left-aligned until the screen switches to the mobile view

> Original issue https://github.com/gnosis/gp-ui/issues/867 by @elena-zh

**Comment by alongoni** [comment]
I think we can close this issue. Now is working fine:
![image](https://user-images.githubusercontent.com/622217/176684425-936cf126-5c4e-4bf1-a9c2-bf9a32b7d2e4.png)
cc. @elena-zh
