### ISSUE TITLE
Change COW token icon

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#227]
1. Open https://explorer.cow.fi/address/0x2dB8323b3766b868AAF6a967E55eEb35C233DE9d or https://explorer.cow.fi/orders/0x7cb03fd2336b53284f566d966cb6c2e701c80e16580cfd8872ac8b5696e1c0e92db8323b3766b868aaf6a967e55eeb35c233de9d63063cbd
2. Verify COW token icon

**AR**: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/1cc7857e-8259-46ff-8a7e-9bba5cb16b39)

**ER**: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/13cd662a-a876-44bf-b0f2-a25c955ac6f4)
New logo: https://drive.google.com/drive/u/0/folders/1LvoYA0qMa58DWxZMxgtia_sS7lrp8cBU

**Comment by alongoni** [comment]
As I understand this icon is provided by Trustwallet.
We need to create a PR in order to add the new token logo.
E.g: 
https://github.com/trustwallet/assets/pull/19338
Others PR made: https://github.com/trustwallet/assets/pulls?q=is%3Apr+cow+is%3Aclosed
cc @alfetopito @ramirotw

**Comment by alfetopito** [comment]
Indeed, it's paid and we have to submit a PR to them as you point out.
I'll raise this internally.

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you
kindly file a support ticket below 
https://forms.gle/7KbQyuY5NoxyrhNz5
