### ISSUE TITLE
Add a tag with environment to the User details table

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#254]
Reported in https://cowservices.slack.com/archives/C036G0J90BU/p1668541647949179

Currently, user details page shows orders both from Prod and Barn environments
It would be great to show now a tag that will indicate the relevant environment for each order.

**Comment by anxolin** [comment]
I think we shouldn't overcomplicated this. In principle, Barn is just a canary environment, is not the production one. 

Adding this information might make normal users from production more confused, and I don't see a big benefit. Plus, will make the UI info more cluttered.

**Comment by elena-zh** [comment]
Closing this for now
