### ISSUE TITLE
A lot of  'https://rpc.gnosischain.com/' requests in console when open a user details page in GC

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#31]
There is a lot of  'dai.poa.network' requests in console when open a user details page in xdai
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/f6f5b2eb-e1db-4a9f-a4cd-70926d2f2f6d)

Is this OK?

> Original issue https://github.com/gnosis/gp-ui/issues/960 by @elena-zh

**Comment by elena-zh** [comment]
Now I can see lots of 'https://rpc.gnosischain.com/' requests:
![image](https://user-images.githubusercontent.com/70885163/198071190-be411328-a3b8-4034-b9f6-428acf8a7f46.png)

**Comment by elena-zh** [comment]
No longer relevant
