### ISSUE TITLE
[Explorer] Batch viewer design

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#34]
We want to add a "batch view".
- Tokens traded
- Volumes
- Graph linking the tokens
- CoWs between orders
- AMMs used
- Gas cost

Example of a batch with several traders https://etherscan.io/tx/0x1eced7428aebc4cd59af3b170bcc960b5fa6aee1459c924eb5f1abe528097eb7

Another example that uses univ2, sushiswap, univ3(via 1inch) https://etherscan.io/tx/0x71cf245169557a344c4aea6aa08801e95892d08c4ede5fc09fd59d578b524ee4

E.g. from from GPv1
![image](https://user-images.githubusercontent.com/622217/127882151-0385917f-054b-44d8-9a5d-04355cd3726f.png)

E.g. from Anxo:
Two graph representations of a settlement. 

- One grouping by address.
- One grouping by token

Ideally, we would need to know if an AMM is involved. We will need to check how is best to get this information. this way, we can show the “path” of execution to the users too.
This is an unrefinated, and undiscussed idea of the two settlement representations:
![image (1)](https://user-images.githubusercontent.com/622217/130087708-eed7a9b2-aa8d-4e69-87c3-85fb1933c1a8.png)

Document for explore libs:
https://docs.google.com/document/d/1cCfvKVCkuyGtpuf1QjKBeNo4Z9cLESDlP3HX2jcdo0g/edit?usp=sharing

> Original issue https://github.com/gnosis/gp-ui/issues/1052 by @alfetopito

**Comment by alfetopito** [comment]
First version is out and the epic was closed https://github.com/cowprotocol/explorer/issues/33
I suggest to keep this issue for reference of the next version/steps
