### ISSUE TITLE
Add 'anchor' for the batch viewer into the page URL

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#41]
originally reported in https://github.com/gnosis/gp-ui/pull/1061#issuecomment-1076358189

It would be nice tp add some kind of an anchor into the URL to separate what Tx view we are using.
I mean, if we see Batch viewer, add #batch into the URL or so?
So a user will be able to share this link and open exactly the viewer, not the list. Also, when a user updates the page, it will also show the viewer.
https://watch.screencastify.com/v/V0tvqMqCZzgtUIRcsfnK

Updated:
- We will improve the link to the Batch Viwer by adding a toogle button or a tab (see screenshots on comments)

> Original issue https://github.com/gnosis/gp-ui/issues/1072 by @elena-zh

**Comment by alongoni** [comment]
Design for the toogle button on Transaction page:

**Comment by alfetopito** [comment]
I'm ok with that suggestion `2`
We do want to have more tabs for other things like partial fills for order details, and keeping the same look and feel I think it makes sense

**Comment by elena-zh** [comment]
Agree with @alfetopito and vote for the 2nd option

**Comment by fairlighteth** [comment]
Agreed as well with @alfetopito 's suggestion.

**Comment by ramirotw** [comment]
So lets go with the 2nd option. Does it make sense to add some icons to the tabs labels? I like icons over plain text labels

**Comment by fairlighteth** [comment]
Yes thought about it as well and forgot to mention: For the simple reason we have the 'graph' option, it might be good to have an icon (for all tabs) to clarify just visually what to expect behind the text label.

**Comment by alfetopito** [comment]
> Yes thought about it as well and forgot to mention: For the simple reason we have the 'graph' option, it might be good to have an icon (for all tabs) to clarify just visually what to expect behind the text label.

Then I vote for the suggested icons for the proposed buttons to be used in the tabs, keeping the labels suggested on option 2:

{List icon} Orders | {Graph icon} Graph
