### ISSUE TITLE
Add  'Avg.execution price' card to the Fills tab

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#448]
Discussion https://cowservices.slack.com/archives/C0361CDG8GP/p1681485565181189
Add  'Avg.execution price' card to the Fills tab of a Partially fillable order with several fills. 
Add it to the 2nd position.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/71103698-5e01-4cbe-82c4-943dd4bc74a2)

Like we do in an order receipt: 
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c7ca2e29-942c-460c-8070-f592751e4c6c)

**Comment by anxolin** [comment]
Fair request. We should do
