### ISSUE TITLE
Surplus value overlaps other fields when it is too big

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#462]
See the example in the https://explorer.cow.fi/address/0x0ac3abf9050d63bda7b105eb0c9faef3e045657a
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/178b270f-b00f-48c6-8e98-5fa445b18f18)

**Expected**: show the surplus nicer

**Comment by anxolin** [comment]
This feels like a extreme case. Tagging @fairlighteth in case is super super low-hanging, but otherwise we put in icebox

**Comment by alfetopito** [comment]
Addressed on https://github.com/cowprotocol/explorer/pull/549
