### ISSUE TITLE
Update repos in the footer

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#52]
URLs navigate to old repos.
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/c2cac0f3-581d-4912-97a2-2e3e45447405)

Expected: 
Settlement contract: https://github.com/cowprotocol/contracts/blob/main/src/contracts/GPv2Settlement.sol
Vault Relayer contract: https://github.com/cowprotocol/contracts/blob/main/src/contracts/GPv2VaultRelayer.sol
Web: v2.7.0: https://github.com/cowprotocol/gp-ui/tree/ (version)

**Comment by anxolin** [comment]
Yes the contracts location is correct, although they point to the latest code in `main` branch. 

We should use the blob of the tagged version. i.e. https://github.com/cowprotocol/contracts/blob/v1.1.2/src/contracts/GPv2VaultRelayer.sol
