### ISSUE TITLE
Add icons to tokens, networks and AMMs in the batch viewer

### ISSUE THREAD

**Issue by ramirotw** [cowprotocol/explorer#57]
**Description**
Currently no icons are shown in the batch viewer, which makes the UI not funny or visually appealing. Lets bring some magic.

**Comment by anxolin** [comment]
Nice! just remember to add also the labels as we discussed. We should have a mapping file based on the rust implementation (where we can find all of the addresses).

**Comment by ramirotw** [comment]
> Nice! just remember to add also the labels as we discussed. We should have a mapping file based on the rust implementation (where we can find all of the addresses).

Yes, that's what we have in mind. The addresses in the rust file I shared had the routers and factories for the AMMs, not the pair pool contract addresses that we should match against to show a friendly name, so we probably need to either run some on chain calls to get which AMM protocol is that pool address from, or write a mapping file but I believe that would be cumbersome as there are many contract addresses for each pair, protocols and networks.

**Comment by ramirotw** [comment]
We show pool addresses in the arrow's tooltip. If we group the AMMs by protocol name instead of pool addresses we might need to rethink a few things to make it work, I'd like to keep the pool address in the tooltip but grouping the transactions by protocol is a nice thing to consider. Maybe having a box as we have with `Ethereum Liquidity` is also a possibility.

**Comment by anxolin** [comment]
Yes, the address is nice. Maybe we can provide the info of all the pools in the tooltip if we want. Anyways, just a suggestion of further improvements on this viewer

**Comment by alfetopito** [comment]
Recent change which can help improving the graph https://metadata.etherscan.io/api-endpoint/address-metadata
