### ISSUE TITLE
Newly created orders do not appear in DEV/BARN explorer

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#63]
The issue is reproducible for https://barn.explorer.cow.fi/ and https://protocol-explorer.dev.gnosisdev.com/

1. Place an order
2. Cancel it OR wait till the order is executed
3. Open the explorer and wait till the order is cancelled/executed

**AR**:
 -  the order status is not updated in the Cowswap app, and then  the order becomes 'Expired' instead of cancelled. 
 - the order does not appear in the User details page on Explorer
- the order is displayed as 'Expired' in the Explorer when it is 'Filled'
- Affiliate program is not working due to this issue
 - However, when I connect the same account in another browser, I'm able to load all the orders from API and see them on Explorer
**Video**: https://watch.screencastify.com/v/sNSJvTS6mQ3bYlqkAKEi
![orders.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/975d1f18-38f5-42ec-86dd-0242a01b1dc4)
![ststuses.jpg](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/ece3e9ef-d4f5-45de-ba2e-8bfb52cea6f6)
![image.png](https://images.zenhubusercontent.com/5f55ec970a2e890ec10f7778/2215d4a1-b4e2-474b-9932-a7f534ed3b86)

**ER**: orders syncing woks as expected. Orders are displayed in a user's details page

**Comment by elena-zh** [comment]
Console does not show any errors 
![image](https://user-images.githubusercontent.com/70885163/162756148-27b1d267-bb6b-4b2d-b9bf-211380e8aeb6.png)

**Comment by anxolin** [comment]
Nice finding! thanks for looking into this

**Comment by alfetopito** [comment]
Devops changed some setting that should address the issue.
We should test again to make sure it has been fixed.

**Comment by elena-zh** [comment]
Fixed!
