### ISSUE TITLE
Add an access to the Batch Viewer on order page

### ISSUE THREAD

**Issue by alongoni** [cowprotocol/explorer#64]
As Anxo mentioned in the [doc for the reiteration on BV,](https://docs.google.com/document/d/12tMl4Cn0gh7rKGJjAjsn4kuQsDu9wfAl_eR5AgDJgsM/edit#) we need to add an access to the BV in the "order details" page.

Draft proposal from Anxo:
![image](https://user-images.githubusercontent.com/622217/163463602-ef3befe7-afa2-4d13-9ada-b0d17416f582.png)

**Comment by alongoni** [comment]
Here we have two approaches:
1. Using a "toogle buttons" ([Figma prototype](https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=2235%3A2885&viewport=241%2C48%2C0.23&scaling=contain&page-id=0%3A1&starting-point-node-id=2235%3A2885))
![image](https://user-images.githubusercontent.com/622217/163464021-e590c5fd-1a66-425f-88d4-73ba1e4187a4.png)
![BV-Order-detail](https://user-images.githubusercontent.com/622217/163464212-cb4b8d84-6e85-4c03-80b7-7adc77ddfbba.png)
Pros: the buttons are more integrated in the UI and show the two options of visualizations. Additionally, these buttons can be used in the transaction list page as well.

2. Using a big button + icon: ([Figma prototype](https://www.figma.com/proto/m7obOydxAhGNmlFYvxTk3Z/GP-Explorer?node-id=2233%3A2585&viewport=241%2C48%2C0.3&scaling=contain&page-id=0%3A1&starting-point-node-id=2233%3A2585))
![image](https://user-images.githubusercontent.com/622217/163466506-7dabb658-de08-4038-8814-d986efdd6422.png)
Pros: this button has a greater presence and impact (including the small BV representation).
Cons: Buttons may be too big. They will look more integrated when we add some stats cards beside them.


cc @anxolin @alfetopito @fairlighteth

**Comment by elena-zh** [comment]
I vote for the 2nd option 🙂

**Comment by alfetopito** [comment]
I vote with Elena for proposal `2`.

The toggle makes sense when on the transaction orders view.

When viewing the order detail view, `list` doesn't give enough context to know list of what.

One idea/suggestion/question: what about putting the button closer the the `transaction hash` row?

Not sure it should be there, just raising it in case someone has an idea on how to integrate the current path to transaction orders list with transaction orders graph button.

**Comment by fairlighteth** [comment]
Chiming in:
- On the order detail page I think showing a toggle between list view and graph view could make sense. But albeit a bit of lost context. So meaning option 1 is not the best choice here for that reason.
- @alfetopito suggested moving the 'View Graph' button closer to the transaction hash row. In terms of contextual relevance between 'transaction hash' and 'View Graph' I would say it is good to bring them closer together.

My suggestion:
- Move the 'View Graph' to the transaction hash row. Rename 'View Graph' to => 'View settlement graph' (or something more descriptive than just 'view graph').
- In the explorer where we can see settled orders in a batch (https://explorer.cow.fi/tx/0xd9db2a90dc2b6ddc07e3b100090b4f596fb8021e7d552aaadf077550e96e621d) I find the toggle to provide the best experience. You can quickly toggle between the two states. 

The only thing I have a harder time with, is the 'Transaction details' page title. I think it should be called 'Batch' or something more descriptive of showing multiple orders in a batch. 

On that same line of thought 'Transaction Hash' could also be made consistent by calling it 'Batch Settlement'. The 'View Graph' then makes much more sense in that context.

**Comment by alongoni** [comment]
Thanks for the feedback!
Design updated:
![BV-Order-detail-v2](https://user-images.githubusercontent.com/622217/163893942-3caa6e60-0d0e-46d3-a35b-68df2776a553.png)

**Comment by fairlighteth** [comment]
I'd try to explore if you could have it be an action/button closer to the 'copy' icon and perhaps less big. Also I feel the icon is too big/too detailed.

**Comment by alongoni** [comment]
It's right! I had the same feeling. Maybe something like this could work better:

![BV-Order-detail](https://user-images.githubusercontent.com/622217/163997036-620d2976-85bc-4ff1-8d2b-1703b77f502f.png)

![BV-Order-detail-1](https://user-images.githubusercontent.com/622217/163997027-b5c045e5-4504-4553-a7b8-b739762840ea.png)

**Comment by alongoni** [comment]
Ok, so for now we will go with this:
Order details page:
![image](https://user-images.githubusercontent.com/622217/164324487-f79b2149-0123-4c72-9bb2-b26158d31a26.png)

**Comment by alfetopito** [comment]
> I'm good with the current proposal. A nitpick, I like more the word "batch" than "settlement" because it points out that we bundle other trades. Although, im not too strong about this one.
> 
> Imo, doing this in a tab was also a good option. Remember we will add soon a tab with the details of the executions of the order. Or at least this was our original plan, and still part of our figma. So it makes sense to add all these complementary informations as tabs.

The only think I have against your suggestion as a tab is that it would be a link to another page rather than a table in the path (/orders)

Happy to revisit this if we decide to load the graph inside the tab when we add more tabs

**Comment by alfetopito** [comment]
Having said that, I believe it's good to go Agustin

**Comment by anxolin** [comment]
> The only think I have against your suggestion as a tab is that it would be a link to another page rather than a table in the path (/orders)

Making it a page I don't see it as something bad. On the contrary, this way someone can share the link. 
@ramirotw mentioned that we would like to be able to share batch representations. So I could see one path for the something like `/orders/0x000..../batch-graph` 

Same as `/tx/0x0000.../batch-graph`
