### ISSUE TITLE
Fills tab in Explorer

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#7]
![image.png](https://images.zenhubusercontent.com/5c4f7d89326c7a5e509d6165/9889e2b3-6b8a-44da-86e5-c53e291bdc0c)

* Tab + page + navigation: 
* Load fills data:
* Table with data:
* widgets: prices:
* widgets: filled percentage:
* widgets: surplus:
* Make sure it looks great in a Mobile: 

> Original issue https://github.com/gnosis/gp-ui/issues/247 by @anxolin

**Comment by anxolin** [comment]
@fairlighteth should we revisit this one and decide if we close and include as part of the "partial fillable" designs or we just leave open and include in our specs for explorer partial fillable task?

**Comment by elena-zh** [comment]
Released
