### ISSUE TITLE
[Batch Viewer] AMMs nodes are displayed only once when involved in multiple interactions

### ISSUE THREAD

**Issue by ramirotw** [cowprotocol/explorer#72]
**Description**
From @fleupold's comment
> Hi, it looks like in the transaction batch view we are only showing 1 interaction when the same address is involved in 2 interactions (e.g. when the Balancer Vault is used for 2 consecutive interactions). E.g. https://explorer.cow.fi/tx/0x99edc43f8ac89986fea0f433f2e87d09483090a776e152e50898e721f9b50210 is missing the WETH<>USDC balancer interaction.

**How to Reproduce**
1. Go to https://explorer.cow.fi/tx/0x99edc43f8ac89986fea0f433f2e87d09483090a776e152e50898e721f9b50210
2. Click on `Show Batch Viewer`
3. `Vault` Balancer node is only displayed once on the `WETH<>NATION` pair and the `WETH<>USDC` pair is missing

**Expected behavior**
Balancer's `Vault` should be displayed twice for the pairs  `WETH<>NATION` and `WETH<>USDC`

**Screenshots**
<img width="911" alt="image" src="https://user-images.githubusercontent.com/3328006/165081442-214b1d8a-33d7-4ae5-85ae-6fb320e0f785.png">

**Additional context**
When creating the graph nodes in https://github.com/cowprotocol/explorer/blob/develop/src/apps/explorer/components/TransanctionBatchGraph/index.tsx#L71-L77 addresses are mapped to ids and they shouldn't as they can appear more than once.

**Comment by MartinquaXD** [comment]
Here is another very complex [example](https://explorer.cow.fi/tx/0x67b9ee6d6d6a96c56ae689c71a588dd1739d98ed4b542b513b7f8896916fd6ee) in case you want more settlements to test.
In this case there are missing a couple of transactions between CoWProtocol and FlashWallet and the route CoW -(USDC)-> UniV3 -(WETH)-> 0x gets taken twice with different amounts.
