### ISSUE TITLE
Make volume chart auto-adjustable when changing a screen width

### ISSUE THREAD

**Issue by elena-zh** [cowprotocol/explorer#75]
Originally reported in https://github.com/cowprotocol/explorer/pull/62#issuecomment-1110902804 (case 3)

 It would be great to make the diagram auto-adjustable when changing a screen width. Also, card's content should be auto-adjustable as well: https://watch.screencastify.com/v/P3ANnXlEwQ8eVFxqzPYu

**Comment by elena-zh** [comment]
Seems to be related to #44

**Comment by elena-zh** [comment]
A proposal to fix https://altoros.slack.com/archives/C03902HBL06/p1651160333279829

**Comment by alongoni** [comment]
Closed by #90

**Comment by elena-zh** [comment]
Added to the #112 issue
