### ISSUE TITLE
Smart quote selection (canonical market)

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#9]
I'm pretty sure this issue was created, but I don't find it now. Maybe is a duplicate. 

The explorer right now doesn't have a strategy to select how to display the price. 

The result is that, for example buying and selling the same token pars will express the price differently. See these 2 orders:
* https://gnosis-protocol.io/rinkeby/orders/0x67f1d68a490a868d1dad5abd52ae16a969f1f6a69824da3f7f472bb1dd77c422424a46612794dbb8000194937834250dc723ffa560af8ff9
* https://gnosis-protocol.io/rinkeby/orders/0xbeab2762dca9e98ed9c25fdf10893a261535cd31d30acdf859fb058902341394424a46612794dbb8000194937834250dc723ffa560af8fe7

![image](https://user-images.githubusercontent.com/2352112/119823251-dfbdfd00-bef4-11eb-9aba-4e1322695a9c.png)

![image](https://user-images.githubusercontent.com/2352112/119823297-eba9bf00-bef4-11eb-9e79-45adbb83d5a8.png)

For example in this case, the price should be expressed in DAI per WETH (by default).

For gpv1 we did a smart selection of the price, that was described here:
https://docs.google.com/document/d/1Hwoi8xBhPiOg-KqoeQEuWsg1WjGIXxrifWbMtvWJlME/edit

We should start with a simple strategy to have a better UX in terms of prices.

> Original issue https://github.com/gnosis/gp-ui/issues/331 by @anxolin

**Comment by anxolin** [comment]
Now that we have the mono-repo, is super simple to share this logic in explorer

@nenadV91 if you get a chance this one would be good to have

**Comment by alfetopito** [comment]
Remember that the Explorer is not in the same mono-repo

**Comment by elena-zh** [comment]
Closing this in favor of cowprotocol/cowswap#3711
